// Code generated by "stringer -type=Token"; DO NOT EDIT.

package main

import "strconv"

const _Token_name = "ILLEGALWSROLLOPARENCPARENOBRKTCBRKTOPERATORNUMBERIDENTEOF"

var _Token_index = [...]uint8{0, 7, 9, 13, 19, 25, 30, 35, 43, 49, 54, 57}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
