FROM golang:alpine

RUN apk add --no-cache git mercurial \
    && go get cloud.google.com/go/logging \
    && go get github.com/aasmall/word2number \
    && go get github.com/wcharczuk/go-chart \
    && go get github.com/aasmall/dicemagic/app/proto \
    && go get google.golang.org/grpc \
    && go get google.golang.org/grpc/reflection \
    && apk del git mercurial

ADD . /go/src/github.com/aasmall/dicemagic/app/server

WORKDIR /go/src/github.com/aasmall/dicemagic/app/server

RUN go install github.com/aasmall/dicemagic/app/server

ENV GOOGLE_APPLICATION_CREDENTIALS "/go/src/github.com/aasmall/dicemagic/dice-api/k8s-dice-magic.json"

ENTRYPOINT /go/bin/server

EXPOSE 50051