FROM golang:alpine

RUN apk add --no-cache shadow \
    && sed -i 's/^CREATE_MAIL_SPOOL=yes/CREATE_MAIL_SPOOL=no/' /etc/default/useradd \
    && groupadd --gid 1000 dicemagic \
    && useradd --uid 1000 --gid dicemagic --shell /bin/sh --create-home dicemagic \
    && apk del shadow 



RUN apk add --no-cache git mercurial \
    && go get cloud.google.com/go/logging \
    && go get github.com/aasmall/word2number \
    && go get github.com/wcharczuk/go-chart \
    && go get github.com/aasmall/dicemagic/app/proto \
    && go get google.golang.org/grpc \
    && go get google.golang.org/grpc/reflection \
    && go get contrib.go.opencensus.io/exporter/stackdriver \
    && go get go.opencensus.io/trace \
    && go get go.opencensus.io/plugin/ocgrpc \
    && apk del git mercurial


USER 1000

ADD . /go/src/github.com/aasmall/dicemagic/app/dice-server

WORKDIR /go/src/github.com/aasmall/dicemagic/app/dice-server

RUN go install github.com/aasmall/dicemagic/app/dice-server

ENV GOOGLE_APPLICATION_CREDENTIALS "/etc/google-default/k8s-dice-magic.json"

ENTRYPOINT /go/bin/dice-server

EXPOSE 50051