// Code generated by "stringer -type=clientType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[normal-0]
	_ = x[snooper-1]
}

const _clientType_name = "normalsnooper"

var _clientType_index = [...]uint8{0, 6, 13}

func (i clientType) String() string {
	if i < 0 || i >= clientType(len(_clientType_index)-1) {
		return "clientType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _clientType_name[_clientType_index[i]:_clientType_index[i+1]]
}
