FROM golang:alpine

RUN apk add --no-cache git mercurial \
    && go get cloud.google.com/go/logging \
    && go get github.com/aasmall/word2number \
    && apk del git mercurial

ADD . /go/src/github.com/aasmall/dicemagic/app

WORKDIR /go/src/github.com/aasmall/dicemagic/app

RUN go install github.com/aasmall/dicemagic/dice-api

ENV GOOGLE_APPLICATION_CREDENTIALS "/go/src/github.com/aasmall/dicemagic/dice-api/k8s-dice-magic.json"

ENTRYPOINT /go/bin/dice-api

EXPOSE 8080