FROM golang:alpine
RUN apk add --no-cache git mercurial hugo

ADD . /go/src/github.com/aasmall/dicemagic/www

WORKDIR /go/src/github.com/aasmall/dicemagic/www

RUN hugo

RUN apk del git mercurial hugo 

RUN go install github.com/aasmall/dicemagic/www

ENTRYPOINT /go/bin/www

EXPOSE 8080