FROM alpine:3.8

RUN apk add --no-cache shadow \
    && sed -i 's/^CREATE_MAIL_SPOOL=yes/CREATE_MAIL_SPOOL=no/' /etc/default/useradd \
    && groupadd --gid 1000 dicemagic \
    && useradd --uid 1000 --gid dicemagic --shell /bin/sh --create-home dicemagic \
    && apk del shadow 

RUN apk add --no-cache lighttpd bash python curl python-dev musl-dev libffi-dev openssl-dev gcc

RUN mkdir /certbot
RUN mkdir /var/www/dicemagic
COPY . /certbot

WORKDIR /certbot

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install virtualenv
RUN pip install certbot
RUN pip install certbot-dns-google
RUN rm get-pip.py

#RUN apk del gcc python-dev musl-dev libffi-dev openssl-dev

RUN chmod a+x renewcerts.sh

ENV GOOGLE_APPLICATION_CREDENTIALS "/etc/certbot-dns/certbot-dns.json"


USER 1000:1000
ENTRYPOINT [ "/bin/bash", "renewcerts.sh" ]

EXPOSE 8080