// Code generated by "stringer -type=ChannelType"; DO NOT EDIT.

package main

import "testing"

func TestChannelType_String(t *testing.T) {
	tests := []struct {
		name string
		i    ChannelType
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("ChannelType.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
