// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dicemagic.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type RollRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Probabilities        bool     `protobuf:"varint,2,opt,name=probabilities,proto3" json:"probabilities,omitempty"`
	Chart                bool     `protobuf:"varint,3,opt,name=chart,proto3" json:"chart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollRequest) Reset()         { *m = RollRequest{} }
func (m *RollRequest) String() string { return proto.CompactTextString(m) }
func (*RollRequest) ProtoMessage()    {}
func (*RollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba8fa741f5f7d8, []int{0}
}

func (m *RollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollRequest.Unmarshal(m, b)
}
func (m *RollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollRequest.Marshal(b, m, deterministic)
}
func (m *RollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollRequest.Merge(m, src)
}
func (m *RollRequest) XXX_Size() int {
	return xxx_messageInfo_RollRequest.Size(m)
}
func (m *RollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollRequest proto.InternalMessageInfo

func (m *RollRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *RollRequest) GetProbabilities() bool {
	if m != nil {
		return m.Probabilities
	}
	return false
}

func (m *RollRequest) GetChart() bool {
	if m != nil {
		return m.Chart
	}
	return false
}

// The response message containing the greetings
type RollResponse struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	DiceSet              *DiceSet `protobuf:"bytes,2,opt,name=DiceSet,proto3" json:"DiceSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollResponse) Reset()         { *m = RollResponse{} }
func (m *RollResponse) String() string { return proto.CompactTextString(m) }
func (*RollResponse) ProtoMessage()    {}
func (*RollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba8fa741f5f7d8, []int{1}
}

func (m *RollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollResponse.Unmarshal(m, b)
}
func (m *RollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollResponse.Marshal(b, m, deterministic)
}
func (m *RollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollResponse.Merge(m, src)
}
func (m *RollResponse) XXX_Size() int {
	return xxx_messageInfo_RollResponse.Size(m)
}
func (m *RollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollResponse proto.InternalMessageInfo

func (m *RollResponse) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *RollResponse) GetDiceSet() *DiceSet {
	if m != nil {
		return m.DiceSet
	}
	return nil
}

type Dice struct {
	Count                int64             `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Sides                int64             `protobuf:"varint,2,opt,name=Sides,proto3" json:"Sides,omitempty"`
	Total                int64             `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	Faces                []int64           `protobuf:"varint,4,rep,packed,name=Faces,proto3" json:"Faces,omitempty"`
	Color                string            `protobuf:"bytes,5,opt,name=Color,proto3" json:"Color,omitempty"`
	Max                  int64             `protobuf:"varint,6,opt,name=Max,proto3" json:"Max,omitempty"`
	Min                  int64             `protobuf:"varint,7,opt,name=Min,proto3" json:"Min,omitempty"`
	DropHighest          int64             `protobuf:"varint,8,opt,name=DropHighest,proto3" json:"DropHighest,omitempty"`
	DropLowest           int64             `protobuf:"varint,9,opt,name=DropLowest,proto3" json:"DropLowest,omitempty"`
	Chart                []byte            `protobuf:"bytes,10,opt,name=Chart,proto3" json:"Chart,omitempty"`
	Probabilities        map[int64]float64 `protobuf:"bytes,11,rep,name=Probabilities,proto3" json:"Probabilities,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dice) Reset()         { *m = Dice{} }
func (m *Dice) String() string { return proto.CompactTextString(m) }
func (*Dice) ProtoMessage()    {}
func (*Dice) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba8fa741f5f7d8, []int{2}
}

func (m *Dice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dice.Unmarshal(m, b)
}
func (m *Dice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dice.Marshal(b, m, deterministic)
}
func (m *Dice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dice.Merge(m, src)
}
func (m *Dice) XXX_Size() int {
	return xxx_messageInfo_Dice.Size(m)
}
func (m *Dice) XXX_DiscardUnknown() {
	xxx_messageInfo_Dice.DiscardUnknown(m)
}

var xxx_messageInfo_Dice proto.InternalMessageInfo

func (m *Dice) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Dice) GetSides() int64 {
	if m != nil {
		return m.Sides
	}
	return 0
}

func (m *Dice) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Dice) GetFaces() []int64 {
	if m != nil {
		return m.Faces
	}
	return nil
}

func (m *Dice) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Dice) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Dice) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Dice) GetDropHighest() int64 {
	if m != nil {
		return m.DropHighest
	}
	return 0
}

func (m *Dice) GetDropLowest() int64 {
	if m != nil {
		return m.DropLowest
	}
	return 0
}

func (m *Dice) GetChart() []byte {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *Dice) GetProbabilities() map[int64]float64 {
	if m != nil {
		return m.Probabilities
	}
	return nil
}

type DiceSet struct {
	Dice                 []*Dice            `protobuf:"bytes,1,rep,name=Dice,proto3" json:"Dice,omitempty"`
	TotalsByColor        map[string]float64 `protobuf:"bytes,2,rep,name=TotalsByColor,proto3" json:"TotalsByColor,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Total                int64              `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	ReString             string             `protobuf:"bytes,4,opt,name=ReString,proto3" json:"ReString,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DiceSet) Reset()         { *m = DiceSet{} }
func (m *DiceSet) String() string { return proto.CompactTextString(m) }
func (*DiceSet) ProtoMessage()    {}
func (*DiceSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba8fa741f5f7d8, []int{3}
}

func (m *DiceSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceSet.Unmarshal(m, b)
}
func (m *DiceSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceSet.Marshal(b, m, deterministic)
}
func (m *DiceSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceSet.Merge(m, src)
}
func (m *DiceSet) XXX_Size() int {
	return xxx_messageInfo_DiceSet.Size(m)
}
func (m *DiceSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceSet.DiscardUnknown(m)
}

var xxx_messageInfo_DiceSet proto.InternalMessageInfo

func (m *DiceSet) GetDice() []*Dice {
	if m != nil {
		return m.Dice
	}
	return nil
}

func (m *DiceSet) GetTotalsByColor() map[string]float64 {
	if m != nil {
		return m.TotalsByColor
	}
	return nil
}

func (m *DiceSet) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiceSet) GetReString() string {
	if m != nil {
		return m.ReString
	}
	return ""
}

func init() {
	proto.RegisterType((*RollRequest)(nil), "proto.RollRequest")
	proto.RegisterType((*RollResponse)(nil), "proto.RollResponse")
	proto.RegisterType((*Dice)(nil), "proto.Dice")
	proto.RegisterMapType((map[int64]float64)(nil), "proto.Dice.ProbabilitiesEntry")
	proto.RegisterType((*DiceSet)(nil), "proto.DiceSet")
	proto.RegisterMapType((map[string]float64)(nil), "proto.DiceSet.TotalsByColorEntry")
}

func init() { proto.RegisterFile("dicemagic.proto", fileDescriptor_63ba8fa741f5f7d8) }

var fileDescriptor_63ba8fa741f5f7d8 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x4d, 0xdb, 0x6d, 0x27, 0x5b, 0x40, 0x86, 0x83, 0xd5, 0xc3, 0x12, 0x22, 0x0e, 0x39,
	0x45, 0xa2, 0x5c, 0x10, 0x5c, 0x10, 0x2d, 0x1f, 0x42, 0x20, 0x21, 0x97, 0x1b, 0xa7, 0x34, 0xb1,
	0xba, 0x16, 0x69, 0x1c, 0x1c, 0x17, 0xe8, 0x2f, 0xe6, 0x2f, 0x70, 0x44, 0x33, 0x0e, 0x4b, 0xac,
	0x0a, 0x71, 0xea, 0xbc, 0xe7, 0xc9, 0xf3, 0x9b, 0x37, 0x2e, 0xdc, 0xa9, 0x74, 0xa9, 0x0e, 0xc5,
	0x5e, 0x97, 0x79, 0x6b, 0x8d, 0x33, 0x7c, 0x42, 0x3f, 0xe9, 0x67, 0x88, 0xa5, 0xa9, 0x6b, 0xa9,
	0xbe, 0x1e, 0x55, 0xe7, 0xf8, 0x5d, 0x88, 0xca, 0x43, 0x25, 0x58, 0xc2, 0xb2, 0xb9, 0xc4, 0x92,
	0x3f, 0x82, 0x45, 0x6b, 0xcd, 0xae, 0xd8, 0xe9, 0x5a, 0x3b, 0xad, 0x3a, 0x31, 0x4a, 0x58, 0x36,
	0x93, 0x21, 0xc9, 0xef, 0xc3, 0xa4, 0xbc, 0x2e, 0xac, 0x13, 0x11, 0x9d, 0x7a, 0x90, 0xbe, 0x83,
	0x4b, 0x2f, 0xde, 0xb5, 0xa6, 0xe9, 0x14, 0xaa, 0xaf, 0xff, 0xaa, 0xaf, 0x0f, 0x15, 0xcf, 0xe0,
	0x62, 0xa3, 0x4b, 0xb5, 0x55, 0x8e, 0x74, 0xe3, 0xd5, 0x6d, 0x6f, 0x2f, 0xef, 0x59, 0xf9, 0xe7,
	0x38, 0xfd, 0x35, 0x82, 0x31, 0xd6, 0x78, 0xd5, 0xda, 0x1c, 0x1b, 0x47, 0x32, 0x91, 0xf4, 0x00,
	0xd9, 0xad, 0xae, 0x7a, 0x7b, 0x91, 0xf4, 0x00, 0xd9, 0x4f, 0xc6, 0x15, 0x35, 0xd9, 0x8a, 0xa4,
	0x07, 0xc8, 0xbe, 0x2e, 0x4a, 0xd5, 0x89, 0x71, 0x12, 0x21, 0x4b, 0xc0, 0xeb, 0xd6, 0xc6, 0x8a,
	0x09, 0xd9, 0xf3, 0x00, 0x2d, 0x7f, 0x28, 0x7e, 0x88, 0x29, 0x7d, 0x8f, 0x25, 0x31, 0xba, 0x11,
	0x17, 0x3d, 0xa3, 0x1b, 0x9e, 0x40, 0xbc, 0xb1, 0xa6, 0x7d, 0xab, 0xf7, 0xd7, 0xaa, 0x73, 0x62,
	0x46, 0x27, 0x43, 0x8a, 0x5f, 0x01, 0x20, 0x7c, 0x6f, 0xbe, 0x63, 0xc3, 0x9c, 0x1a, 0x06, 0x0c,
	0xdd, 0x4d, 0xf1, 0x41, 0xc2, 0xb2, 0x4b, 0xe9, 0x01, 0xdf, 0xc0, 0xe2, 0x63, 0x10, 0x7d, 0x9c,
	0x44, 0x59, 0xbc, 0xba, 0x1a, 0x44, 0x94, 0x07, 0x0d, 0xaf, 0x1a, 0x67, 0x4f, 0x32, 0xfc, 0x68,
	0xf9, 0x02, 0xf8, 0x79, 0x13, 0x4e, 0xf1, 0x45, 0x9d, 0xfa, 0x0c, 0xb1, 0x44, 0x0f, 0xdf, 0x8a,
	0xfa, 0xa8, 0x28, 0x41, 0x26, 0x3d, 0x78, 0x36, 0x7a, 0xca, 0xd2, 0x9f, 0xec, 0x66, 0x4b, 0xfc,
	0x81, 0xdf, 0x82, 0x60, 0x64, 0x25, 0x1e, 0x58, 0x91, 0x7e, 0x3d, 0x6f, 0x60, 0x41, 0x29, 0x77,
	0x2f, 0x4f, 0x3e, 0xce, 0x11, 0x75, 0x3e, 0x0c, 0xf7, 0x9a, 0x07, 0x3d, 0xbd, 0xef, 0x80, 0xfb,
	0xc7, 0xee, 0x96, 0x30, 0x93, 0x6a, 0xeb, 0xac, 0x6e, 0xf6, 0x62, 0x4c, 0x8b, 0xba, 0xc1, 0x38,
	0xe9, 0xb9, 0xec, 0x70, 0xd2, 0xf9, 0x7f, 0x26, 0x5d, 0x3d, 0x87, 0x29, 0x3e, 0x58, 0x65, 0xf9,
	0x63, 0x18, 0x63, 0xc5, 0x79, 0xef, 0x7b, 0xf0, 0x27, 0x59, 0xde, 0x0b, 0x38, 0xff, 0xb6, 0xd3,
	0x5b, 0xbb, 0x29, 0xb1, 0x4f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x49, 0xa2, 0x74, 0x6b,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RollerClient is the client API for Roller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RollerClient interface {
	// Rolls dice
	Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error)
}

type rollerClient struct {
	cc *grpc.ClientConn
}

func NewRollerClient(cc *grpc.ClientConn) RollerClient {
	return &rollerClient{cc}
}

func (c *rollerClient) Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error) {
	out := new(RollResponse)
	err := c.cc.Invoke(ctx, "/proto.Roller/Roll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollerServer is the server API for Roller service.
type RollerServer interface {
	// Rolls dice
	Roll(context.Context, *RollRequest) (*RollResponse, error)
}

func RegisterRollerServer(s *grpc.Server, srv RollerServer) {
	s.RegisterService(&_Roller_serviceDesc, srv)
}

func _Roller_Roll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollerServer).Roll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Roller/Roll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollerServer).Roll(ctx, req.(*RollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Roller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Roller",
	HandlerType: (*RollerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Roll",
			Handler:    _Roller_Roll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dicemagic.proto",
}
